spring.datasource.url=jdbc:postgresql://dpg-d85uomjbc2fs73f663kg:5432/bankdb_62gr
spring.datasource.username=bankdb_62gr_user
spring.datasource.password=jkEJTy12NMUW4LDBBzXMjzIf4kdIMXvc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

spring.datasource.hikari.initialization-fail-timeout=0