spring.datasource.url=jdbc:postgresql://dpg-d779vanafjfc73dcchlg-a.oregon-postgres.render.com:5432/bankdb_eg58
spring.datasource.username=bankdb_eg58_user
spring.datasource.password=P3KBcp3ymWMYSRJ8M9t6QuKssbkx3L70

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

# 🔥 ADD THIS (IMPORTANT)
spring.datasource.hikari.initialization-fail-timeout=0